
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='diagrams',
    version='0.12.0',
    description='Diagram as Code',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://diagrams.mingrammer.com", "repository": "https://github.com/mingrammer/diagrams"},
    author='mingrammer',
    author_email='mingrammer@gmail.com',
    license='MIT',
    packages=['diagrams', 'diagrams.alibabacloud', 'diagrams.aws', 'diagrams.azure', 'diagrams.base', 'diagrams.custom', 'diagrams.gcp', 'diagrams.k8s', 'diagrams.oci', 'diagrams.onprem', 'diagrams.programming'],
    package_dir={"": "."},
    install_requires=['contextvars==2.*,>=2.4.0; python_version == "3.6.*" and python_version >= "3.6.0"', 'dephell==0.*,>=0.8.3', 'graphviz==0.*,>=0.13.2', 'jinja2==2.*,>=2.10.0'],
    extras_require={"dev": ["black==19.*,>=19.0.0", "isort==4.*,>=4.3.0", "pylint==2.*,>=2.4.0", "pytest==3.*,>=3.0.0", "rope==0.*,>=0.14.0"]},
    include_package_data=True,
)
