# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Api(_OnPrem):
    _type = "api"
    _icon_dir = "resources/onprem/api"


class Istio(_Api):
    _icon = "istio.png"


class Kong(_Api):
    _icon = "kong.png"


class Redhat3Scale(_Api):
    _icon = "redhat3scale.png"


class Tyk(_Api):
    _icon = "tyk.png"


class Umbrella(_Api):
    _icon = "umbrella.png"


# Aliases
