# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Apigateway(_OnPrem):
    _type = "apigateway"
    _icon_dir = "resources/onprem/apigateway"


class Istio(_Apigateway):
    _icon = "istio.png"


class Kong(_Apigateway):
    _icon = "kong.png"


class Redhat3Scale(_Apigateway):
    _icon = "redhat3scale.png"


class Tyk(_Apigateway):
    _icon = "tyk.png"


class Umbrella(_Apigateway):
    _icon = "umbrella.png"


# Aliases
