# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _App(_OnPrem):
    _type = "app"
    _icon_dir = "resources/onprem/app"


class Gunicorn(_App):
    _icon = "gunicorn.png"


class Javaee(_App):
    _icon = "javaee.png"


class Jboss(_App):
    _icon = "jboss.png"


class Tomcat(_App):
    _icon = "tomcat.png"


class Uvicorn(_App):
    _icon = "uvicorn.png"


class Weblogic(_App):
    _icon = "weblogic.png"


class Websphere(_App):
    _icon = "websphere.png"


class Wildfly(_App):
    _icon = "wildfly.png"


# Aliases
