# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Appserver(_OnPrem):
    _type = "appserver"
    _icon_dir = "resources/onprem/appserver"


class Gunicorn(_Appserver):
    _icon = "gunicorn.png"


class Javaee(_Appserver):
    _icon = "javaee.png"


class Jboss(_Appserver):
    _icon = "jboss.png"


class Tomcat(_Appserver):
    _icon = "tomcat.png"


class Uvicorn(_Appserver):
    _icon = "uvicorn.png"


class Weblogic(_Appserver):
    _icon = "weblogic.png"


class Websphere(_Appserver):
    _icon = "websphere.png"


class Wildfly(_Appserver):
    _icon = "wildfly.png"


# Aliases
