# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Bus(_OnPrem):
    _type = "bus"
    _icon_dir = "resources/onprem/bus"


class Activemq(_Bus):
    _icon = "activemq.png"


class Celery(_Bus):
    _icon = "celery.png"


class FuseEsb(_Bus):
    _icon = "fuse-esb.png"


class Ibmmq(_Bus):
    _icon = "ibmmq.png"


class Kafka(_Bus):
    _icon = "kafka.png"


class Rabbitmq(_Bus):
    _icon = "rabbitmq.png"


class Solace(_Bus):
    _icon = "solace.png"


class Sonicmq(_Bus):
    _icon = "sonicmq.png"


class Zeromq(_Bus):
    _icon = "zeromq.png"


# Aliases
