# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Callcenter(_OnPrem):
    _type = "callcenter"
    _icon_dir = "resources/onprem/callcenter"


class Asterisk(_Callcenter):
    _icon = "asterisk.png"


class Vicidial(_Callcenter):
    _icon = "vicidial.png"


# Aliases
