# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Chat(_OnPrem):
    _type = "chat"
    _icon_dir = "resources/onprem/chat"


class Lhc(_Chat):
    _icon = "lhc.png"


# Aliases
