# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Cms(_OnPrem):
    _type = "cms"
    _icon_dir = "resources/onprem/cms"


class Joomla(_Cms):
    _icon = "joomla.png"


class Pwb(_Cms):
    _icon = "pwb.png"


class Wagtail(_Cms):
    _icon = "wagtail.png"


# Aliases
