# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Conferencing(_OnPrem):
    _type = "conferencing"
    _icon_dir = "resources/onprem/conferencing"


class Jitsi(_Conferencing):
    _icon = "jitsi.png"


# Aliases
