# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Config(_OnPrem):
    _type = "config"
    _icon_dir = "resources/onprem/config"


class Etcd(_Config):
    _icon = "etcd.png"


class Zookeeper(_Config):
    _icon = "zookeeper.png"


# Aliases
