# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Crm(_OnPrem):
    _type = "crm"
    _icon_dir = "resources/onprem/crm"


class Suitecrm(_Crm):
    _icon = "suitecrm.png"


class Vtiger(_Crm):
    _icon = "vtiger.png"


# Aliases
