# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Ecm(_OnPrem):
    _type = "ecm"
    _icon_dir = "resources/onprem/ecm"


class Alfresco(_Ecm):
    _icon = "alfresco.png"


class Mayanedms(_Ecm):
    _icon = "mayanedms.png"


class Nuxeo(_Ecm):
    _icon = "nuxeo.png"


# Aliases
