# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Ecommerce(_OnPrem):
    _type = "ecommerce"
    _icon_dir = "resources/onprem/ecommerce"


class Saleor(_Ecommerce):
    _icon = "saleor.png"


# Aliases
