# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Erp(_OnPrem):
    _type = "erp"
    _icon_dir = "resources/onprem/erp"


class Erpnext(_Erp):
    _icon = "erpnext.png"


class Odoo(_Erp):
    _icon = "odoo.png"


# Aliases
