# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _F5(_OnPrem):
    _type = "f5"
    _icon_dir = "resources/onprem/f5"


class Appliance(_F5):
    _icon = "appliance.png"


class F5(_F5):
    _icon = "f5.png"


class Ltm(_F5):
    _icon = "ltm.png"


class Swgs(_F5):
    _icon = "swgs.png"


class Viprion(_F5):
    _icon = "viprion.png"


# Aliases
