# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Learning(_OnPrem):
    _type = "learning"
    _icon_dir = "resources/onprem/learning"


class Moodle(_Learning):
    _icon = "moodle.png"


# Aliases
