# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Marketing(_OnPrem):
    _type = "marketing"
    _icon_dir = "resources/onprem/marketing"


class Mautic(_Marketing):
    _icon = "mautic.png"


# Aliases
