# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Mgmt(_OnPrem):
    _type = "mgmt"
    _icon_dir = "resources/onprem/mgmt"


class Openproject(_Mgmt):
    _icon = "openproject.png"


class Redmine(_Mgmt):
    _icon = "redmine.png"


# Aliases
