# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Network(_OnPrem):
    _type = "network"
    _icon_dir = "resources/onprem/network"


class Internet(_Network):
    _icon = "internet.png"


# Aliases

ETCD = Etcd
HAProxy = Haproxy
PFSense = Pfsense
VyOS = Vyos
