# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Os(_OnPrem):
    _type = "os"
    _icon_dir = "resources/onprem/os"


class Centos(_Os):
    _icon = "centos.png"


class Debian(_Os):
    _icon = "debian.png"


class Redhat(_Os):
    _icon = "redhat.png"


# Aliases
