# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Realtime(_OnPrem):
    _type = "realtime"
    _icon_dir = "resources/onprem/realtime"


class Deepstreamio(_Realtime):
    _icon = "deepstreamio.png"


class Socketsio(_Realtime):
    _icon = "socketsio.png"


# Aliases
