# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Rules(_OnPrem):
    _type = "rules"
    _icon_dir = "resources/onprem/rules"


class Drools(_Rules):
    _icon = "drools.png"


class Openltablets(_Rules):
    _icon = "openltablets.png"


# Aliases
