# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Security(_OnPrem):
    _type = "security"
    _icon_dir = "resources/onprem/security"


class CloudAdc(_Security):
    _icon = "cloud-adc.png"


class CloudPortal(_Security):
    _icon = "cloud-portal.png"


class Gluu(_Security):
    _icon = "gluu.png"


class LockinContainer(_Security):
    _icon = "lockin-container.png"


class Openldap(_Security):
    _icon = "openldap.png"


class Openvas(_Security):
    _icon = "openvas.png"


class RadarDetection(_Security):
    _icon = "radar-detection.png"


class Trivy(_Security):
    _icon = "trivy.png"


class UserValid(_Security):
    _icon = "user-valid.png"


class Vault(_Security):
    _icon = "vault.png"


class Vyos(_Security):
    _icon = "vyos.png"


# Aliases
