# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Security(_OnPrem):
    _type = "security"
    _icon_dir = "resources/onprem/security"


class Gluu(_Security):
    _icon = "gluu.png"


class Openldap(_Security):
    _icon = "openldap.png"


class Openvas(_Security):
    _icon = "openvas.png"


class Trivy(_Security):
    _icon = "trivy.png"


class Vault(_Security):
    _icon = "vault.png"


class Vyos(_Security):
    _icon = "vyos.png"


# Aliases
