# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Shortener(_OnPrem):
    _type = "shortener"
    _icon_dir = "resources/onprem/shortener"


class Pygmy(_Shortener):
    _icon = "pygmy.png"


class Yourls(_Shortener):
    _icon = "yourls.png"


# Aliases
