# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Storage(_OnPrem):
    _type = "storage"
    _icon_dir = "resources/onprem/storage"


class ArrayCilinder(_Storage):
    _icon = "array-cilinder.png"


class Array(_Storage):
    _icon = "array.png"


class Database(_Storage):
    _icon = "database.png"


class Nas(_Storage):
    _icon = "nas.png"


class San(_Storage):
    _icon = "san.png"


# Aliases
