# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Survey(_OnPrem):
    _type = "survey"
    _icon_dir = "resources/onprem/survey"


class Lms(_Survey):
    _icon = "lms.png"


# Aliases
