# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Web(_OnPrem):
    _type = "web"
    _icon_dir = "resources/onprem/web"


class Apache(_Web):
    _icon = "apache.png"


class Caddy(_Web):
    _icon = "caddy.png"


class Consul(_Web):
    _icon = "consul.png"


class Envoy(_Web):
    _icon = "envoy.png"


class Haproxy(_Web):
    _icon = "haproxy.png"


class Linkerd(_Web):
    _icon = "linkerd.png"


class Nginx(_Web):
    _icon = "nginx.png"


class Pfsense(_Web):
    _icon = "pfsense.png"


class Pomerium(_Web):
    _icon = "pomerium.png"


class Traefik(_Web):
    _icon = "traefik.png"


# Aliases
