# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OnPrem


class _Workflow(_OnPrem):
    _type = "workflow"
    _icon_dir = "resources/onprem/workflow"


class Bonitabpm(_Workflow):
    _icon = "bonitabpm.png"


class Camunda(_Workflow):
    _icon = "camunda.png"


class Digdag(_Workflow):
    _icon = "digdag.png"


class Joget(_Workflow):
    _icon = "joget.png"


class Kubeflow(_Workflow):
    _icon = "kubeflow.png"


class Nifi(_Workflow):
    _icon = "nifi.png"


class Viewflow(_Workflow):
    _icon = "viewflow.png"


# Aliases

KubeFlow = Kubeflow
NiFi = Nifi
